from __future__ import annotations

import argparse
import json
import logging
import os
import stat
from pathlib import Path
from typing import Any

from src.adapters.polymarket_live import PolymarketLiveConfig, probe_sdk

DEFAULT_GENERATED_ENV = "/home/noel/polylens/.polymarket.env.generated"


def main() -> None:
    logging.disable(logging.CRITICAL)
    parser = argparse.ArgumentParser(description="Polymarket L2 credential setup helper")
    parser.add_argument("--json", action="store_true", default=True)
    parser.add_argument("--no-write-env", action="store_true", help="Do not write .polymarket.env.generated")
    args = parser.parse_args()
    payload = build_credentials_setup(write_env_file=not args.no_write_env)
    print(json.dumps(payload, indent=2, sort_keys=True, default=str))


def build_credentials_setup(
    *,
    write_env_file: bool = True,
    env_file_path: str = DEFAULT_GENERATED_ENV,
) -> dict[str, Any]:
    cfg = PolymarketLiveConfig.from_env()
    input_flags = {
        "POLYMARKET_PRIVATE_KEY_present": bool(cfg.private_key),
        "POLYMARKET_FUNDER_present": bool(cfg.funder),
        "POLYMARKET_SIGNATURE_TYPE": cfg.signature_type,
        "POLYMARKET_CHAIN_ID": cfg.chain_id,
        "POLYMARKET_CLOB_HOST": cfg.clob_host,
    }
    l2_present = bool(cfg.api_key and cfg.api_secret and cfg.api_passphrase)

    base = {
        "input": input_flags,
        "post_order_called": False,
        "sent": False,
    }

    if l2_present:
        return {
            **base,
            "status": "ok",
            "action": "skipped_derivation",
            "reason": "l2_credentials_already_present",
            "derived": False,
            "l2": {
                "api_key_present": True,
                "api_secret_present": True,
                "api_passphrase_present": True,
            },
            "env_file": None,
        }

    if not cfg.private_key:
        return {
            **base,
            "status": "not_ready",
            "action": "blocked",
            "reason": "POLYMARKET_PRIVATE_KEY_missing",
            "derived": False,
            "l2": {
                "api_key_present": False,
                "api_secret_present": False,
                "api_passphrase_present": False,
            },
            "env_file": None,
        }

    sdk_probe = probe_sdk()
    if not sdk_probe.get("sdk_available"):
        return {
            **base,
            "status": "not_ready",
            "action": "blocked",
            "reason": "polymarket_sdk_not_available",
            "derived": False,
            "l2": {
                "api_key_present": False,
                "api_secret_present": False,
                "api_passphrase_present": False,
            },
            "env_file": None,
            "sdk_package": sdk_probe.get("sdk_package"),
        }

    try:
        api_creds = derive_l2_api_credentials(cfg)
    except Exception as exc:
        return {
            **base,
            "status": "not_ready",
            "action": "blocked",
            "reason": "l2_derivation_failed",
            "detail": str(exc),
            "derived": False,
            "l2": {
                "api_key_present": False,
                "api_secret_present": False,
                "api_passphrase_present": False,
            },
            "env_file": None,
        }

    l2_flags = {
        "api_key_present": bool(_cred_value(api_creds, "api_key")),
        "api_secret_present": bool(_cred_value(api_creds, "api_secret")),
        "api_passphrase_present": bool(_cred_value(api_creds, "api_passphrase")),
    }
    env_file_meta = None
    if write_env_file and all(l2_flags.values()):
        env_file_meta = write_generated_env_file(cfg, api_creds, env_file_path)

    return {
        **base,
        "status": "ok" if all(l2_flags.values()) else "not_ready",
        "action": "derived_l2_credentials",
        "reason": None if all(l2_flags.values()) else "derived_credentials_incomplete",
        "derived": True,
        "derivation_method": "create_or_derive_api_key",
        "l2": l2_flags,
        "env_file": env_file_meta,
    }


def derive_l2_api_credentials(cfg: PolymarketLiveConfig) -> Any:
    from py_clob_client_v2 import ClobClient

    client = ClobClient(
        cfg.clob_host,
        chain_id=cfg.chain_id,
        key=cfg.private_key,
        signature_type=cfg.signature_type,
        funder=cfg.funder,
    )
    return client.create_or_derive_api_key()


def write_generated_env_file(cfg: PolymarketLiveConfig, api_creds: Any, path: str) -> dict[str, Any]:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by polymarket_credentials_setup.py",
        "# DO NOT COMMIT — source with: set -a && source .polymarket.env.generated && set +a",
        f"POLYMARKET_PRIVATE_KEY={cfg.private_key}",
        f"POLYMARKET_API_KEY={_cred_value(api_creds, 'api_key')}",
        f"POLYMARKET_API_SECRET={_cred_value(api_creds, 'api_secret')}",
        f"POLYMARKET_API_PASSPHRASE={_cred_value(api_creds, 'api_passphrase')}",
    ]
    if cfg.funder:
        lines.append(f"POLYMARKET_FUNDER={cfg.funder}")
    if cfg.signature_type is not None:
        lines.append(f"POLYMARKET_SIGNATURE_TYPE={cfg.signature_type}")
    lines.append(f"POLYMARKET_CHAIN_ID={cfg.chain_id}")
    lines.append(f"POLYMARKET_CLOB_HOST={cfg.clob_host}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(target, stat.S_IRUSR | stat.S_IWUSR)
    mode = stat.S_IMODE(target.stat().st_mode)
    return {
        "path": str(target),
        "written": True,
        "mode_octal": oct(mode),
        "mode_is_600": mode == 0o600,
    }


def _cred_value(api_creds: Any, field: str) -> str:
    if isinstance(api_creds, dict):
        return str(api_creds.get(field) or "")
    return str(getattr(api_creds, field, "") or "")


if __name__ == "__main__":
    main()
